name: uid
description: DICOM UIDs
version: 0.6.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/uid

environment:
  sdk: ^1.24.2

dependencies:
  binary: ^0.1.3
  bignum: ^0.1.0
  path: ^1.4.2
# uses only string/ascii.dart
  string:
    path: C:/odw/sdk/string
    version: ^0.6.1
  uuid:
    path: C:/odw/sdk/uuid
    version: ^0.6.1

dev_dependencies:
  system:
    path: C:/odw/sdk/system
    version: ^0.6.1
  test: ^0.12.0
