name: uid
description: DICOM UIDs
version: 0.6.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/uid

environment:
  sdk: ^1.24.2

dependencies:
# uses only string/ascii.dart
  system:
    path: C:/odw/sdk/system
    version: ^0.6.3
  bignum: ^0.1.0
  uuid:
    path: C:/odw/sdk/uuid
    version: ^0.6.1

dev_dependencies:
  test: ^0.12.0
