name: uid
description: DICOM UIDs
version: 0.6.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/uid

environment:
  sdk: ^1.24.2

dependencies:
  system:
    path: C:/odw/sdk/system
    version: ^0.6.0
  uuid:
    path: C:/odw/sdk/uuid
    version: ^0.6.0

dev_dependencies:
  common:
    path: C:/odw/sdk/common
    version: ^0.6.0
  test: ^0.12.0
