name: uid
description: DICOM UIDs
version: 0.6.0
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/uid

environment:
  sdk: ^1.24.2

dependencies:
  args: any
  path: any
  common:
    path: C:/odw/sdk/common
    version: ^0.5.6
  uuid:
    path: C:/odw/sdk/uuid
    version: ^0.6.0

dev_dependencies:
  test: ^0.12.0
